### ISSUE TITLE
ios 15 emojis

### ISSUE THREAD

**Issue by yevgenPaykey** [jonghyun-kim/DumpEmoji#1]
Hey. Thanks for this fork with ios 14.5 emojis. I'd like to know about the procedure of adding new emojis for 15+
Maybe you can send me some manual so I can update it?

**Comment by yevgenPaykey** [comment]
@jonghyun-kim

**Comment by jonghyun-kim** [comment]
@yevgenPaykey 

Download iOS project and build and run.
Then taps `Dump` button in the app. You can see the dump files in `/your_home/` on Mac

<img width="373" alt="Screenshot 2022-04-04 at 7 29 29 PM" src="https://user-images.githubusercontent.com/13844979/161598987-f944157b-65c9-4978-86b3-022c1141569e.png">


---

※  Created iOS 15.4 emoji dumps and commit it on https://github.com/jonghyun-kim/DumpEmoji/commit/aa8262661d0f8b02400101f86bcb9da13b4911be

**Comment by yevgenPaykey** [comment]
wow thanks!
